"""add petId to reviews table2

Revision ID: 178392c4a7e0
Revises: 5bec09de1b25
Create Date: 2025-03-26 19:04:24.678448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178392c4a7e0'
down_revision = '5bec09de1b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_reviews_petId_pets', 'pets', ['petId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_petId_pets', type_='foreignkey')
        batch_op.drop_column('petId')

    # ### end Alembic commands ###
