"""changes to user table

Revision ID: 685c5683450e
Revises: 15cfb1c8e6cb
Create Date: 2025-02-26 14:45:25.664306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '685c5683450e'
down_revision = '15cfb1c8e6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kids', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('hasBackyard', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('houseTrained', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('specialNeeds', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('otherPets', sa.Enum('none', 'dogsOnly', 'catsOnly', 'both', 'other'), nullable=False))
        batch_op.drop_column('careAndBehavior')
        batch_op.drop_column('household')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('household', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('careAndBehavior', sqlite.JSON(), nullable=False))
        batch_op.drop_column('otherPets')
        batch_op.drop_column('specialNeeds')
        batch_op.drop_column('houseTrained')
        batch_op.drop_column('hasBackyard')
        batch_op.drop_column('kids')

    # ### end Alembic commands ###
