"""update models

Revision ID: 726935c5847d
Revises: 685c5683450e
Create Date: 2025-02-26 20:14:59.717550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726935c5847d'
down_revision = '685c5683450e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=255), nullable=False),
    sa.Column('lastName', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('kids', sa.Boolean(), nullable=False),
    sa.Column('hasBackyard', sa.Boolean(), nullable=False),
    sa.Column('otherPets', sa.Enum('none', 'dogsOnly', 'catsOnly', 'both', 'other'), nullable=False),
    sa.Column('petExperience', sa.Enum('firstTime', 'previous', 'current', name='pet_experience'), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('radius', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ideal_dog_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('houseTrained', sa.Boolean(), nullable=False),
    sa.Column('specialNeeds', sa.Boolean(), nullable=False),
    sa.Column('idealAge', sa.Enum('noPreference', 'puppy', 'young', 'adult', 'senior', name='ideal_age'), nullable=False),
    sa.Column('idealSex', sa.Enum('noPreference', 'male', 'female', name='ideal_sex'), nullable=False),
    sa.Column('idealSize', sa.Enum('noPreference', 'small', 'medium', 'large', 'xl', name='ideal_size'), nullable=False),
    sa.Column('lifestyle', sa.Enum('noPreference', 'veryActive', 'active', 'laidback', 'lapPet', name='lifestyle'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sellerId', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('vaccinated', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('ownerSurrender', sa.Boolean(), nullable=False),
    sa.Column('kids', sa.Boolean(), nullable=False),
    sa.Column('hasBackyard', sa.Boolean(), nullable=False),
    sa.Column('houseTrained', sa.Boolean(), nullable=False),
    sa.Column('specialNeeds', sa.Boolean(), nullable=False),
    sa.Column('otherPets', sa.Enum('none', 'dogsOnly', 'catsOnly', 'both', 'other'), nullable=False),
    sa.Column('age', sa.Enum('puppy', 'young', 'adult', 'senior', name='age'), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large', 'xl', name='size'), nullable=False),
    sa.Column('adoptionStatus', sa.Enum('available', 'pendingAdoption', 'adopted', name='adoption_status'), nullable=False),
    sa.Column('loveLanguage', sa.Enum('physicalTouch', 'treats', 'play', 'training', 'independent', name='love_language'), nullable=False),
    sa.Column('lifestyle', sa.Enum('veryActive', 'active', 'laidback', 'lapPet', name='lifestyle'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sellerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sellerId', sa.Integer(), nullable=False),
    sa.Column('reviewerId', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=False),
    sa.Column('receiverId', sa.Integer(), nullable=False),
    sa.Column('petId', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petId'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId1', sa.Integer(), nullable=False),
    sa.Column('userId2', sa.Integer(), nullable=False),
    sa.Column('petId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', name='match-status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petId'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['userId1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petId', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('preview', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['petId'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_images')
    op.drop_table('matches')
    op.drop_table('chat_history')
    op.drop_table('reviews')
    op.drop_table('pets')
    op.drop_table('ideal_dog_preferences')
    op.drop_table('users')
    # ### end Alembic commands ###
