"""any changes?

Revision ID: 81b7b787680a
Revises: e1f76a4bdb25
Create Date: 2025-02-27 20:09:15.470594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b7b787680a'
down_revision = 'e1f76a4bdb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideal_dog_preferences', schema=None) as batch_op:
        batch_op.alter_column('houseTrained',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('specialNeeds',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('idealAge',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('idealSex',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('idealSize',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('lifestyle',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideal_dog_preferences', schema=None) as batch_op:
        batch_op.alter_column('lifestyle',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('idealSize',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('idealSex',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('idealAge',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('specialNeeds',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('houseTrained',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
